extends: default

override: {}

ignore:
  - "**/.beads/**"

rules:
  document-start: disable
  truthy: disable
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent
